# Generated by Django 3.2.8 on 2022-02-02 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220201_0520'),
        ('teams', '0003_capitalize_team_shareable_uids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to='users.apiuser'),
        ),
    ]
