# Generated by Django 3.2.8 on 2022-02-03 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_alter_obstacle_challenge'),
        ('scoring', '0002_create_challenge_scoring_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeScoring',
            fields=[
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='scoring', serialize=False, to='challenges.challenge')),
                ('threshold_sum', models.DecimalField(decimal_places=3, max_digits=16)),
                ('xp_base_unit', models.DecimalField(decimal_places=3, max_digits=16)),
            ],
            options={
                'db_table': 'scoring_challenge_scoring_view',
                'managed': False,
            },
        ),
    ]
