# Generated by Django 3.2.8 on 2022-02-08 11:00

from django.db import migrations, models
import django.db.models.deletion


def add_supplemental_xp(apps, schema_editor):
    SupplementalXPReward = apps.get_model("scoring", "SupplementalXPReward")
    UserSupplementalXP = apps.get_model("scoring", "UserSupplementalXP")
    UserProfile = apps.get_model("users", "UserProfile")

    onboarding_xp_reward, _ = SupplementalXPReward.objects.get_or_create(
        reward_type="O",
        defaults={
            "xp_value": 100,
            "description": "Reward for onboarding completion",
        }
    )

    for profile in UserProfile.objects.filter(nickname__isnull=False):
        UserSupplementalXP.objects.get_or_create(
            user_profile=profile,
            supplemental_xp_reward=onboarding_xp_reward,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_update_user_obstacle_view'),
        ('scoring', '0003_challengescoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementalXPReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('O', 'Onboarding complete')], max_length=1)),
                ('xp_value', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSupplementalXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('supplemental_xp_reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.supplementalxpreward')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplemental_xps', to='users.userprofile')),
            ],
        ),
        migrations.RunPython(
            add_supplemental_xp,
            migrations.RunPython.noop,
        ),
    ]
