# Generated by Django 3.2.8 on 2022-02-25 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_supplementalxpreward_usersupplementalxp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSupplementalXP',
        ),
    ]
