# Generated by Django 3.2.8 on 2022-02-01 05:20

import api.users.models.avatar
from django.db import migrations, models
import django.db.models.deletion
import schoolyard.models.relative_file_path_model_field


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_update_user_obstacle_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('model_asset', schoolyard.models.relative_file_path_model_field.RelativeFilePathModelField(match='.*.glb', max_length=1024, path=api.users.models.avatar.model_asset_path)),
                ('metadata_asset', schoolyard.models.relative_file_path_model_field.RelativeFilePathModelField(match='.*.json', max_length=1024, path=api.users.models.avatar.metadata_asset_path)),
            ],
        ),
        migrations.CreateModel(
            name='UserColorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_rgb', models.CharField(max_length=8, verbose_name='Background RGB')),
                ('closest_css3_color', models.CharField(max_length=64, verbose_name='Closest CSS3 Color (BG)')),
            ],
            options={
                'verbose_name': 'User Color Profile',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.avatar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bg_color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.usercolorprofile', verbose_name='BG Color'),
        ),
    ]
