# Generated by Django 3.2.8 on 2022-02-25 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_delete_usersupplementalxp'),
        ('users', '0008_avatar_static_image_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSupplementalXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('supplemental_xp_reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.supplementalxpreward')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplemental_xps', to='users.userprofile')),
            ],
        ),
    ]
