# Generated by Django 3.2.8 on 2022-01-18 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObstacleActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('amount_registered', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
