# Generated by Django 3.2.8 on 2022-01-18 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obstacleactivityevent',
            name='api_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.apiuser'),
        ),
        migrations.AddField(
            model_name='obstacleactivityevent',
            name='obstacle_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obstacle_activity_events', to='users.obstacleactivitywindow'),
        ),
    ]
