# Generated by Django 3.2.8 on 2022-02-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obstacleactivityevent',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
