# Generated by Django 3.2.8 on 2022-01-18 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challenges.challengecategory'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='color_profile',
            field=models.ForeignKey(help_text='The initial value is randomly selected.', on_delete=django.db.models.deletion.PROTECT, to='challenges.challengecolorprofile', verbose_name='Color Profile'),
        ),
    ]
